# Generated by Django 5.2.3 on 2025-06-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora',
        ),
    ]
