# Generated by Django 5.2.3 on 2025-06-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_diaferiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dias',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de días'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacio_techado',
            field=models.BooleanField(default=False, verbose_name='¿Cuenta con espacio de 2x2mt techado?'),
        ),
    ]
