# Generated by Django 5.2.3 on 2025-06-21 04:38

# --- PASO 1: AÑADIR ESTOS IMPORTS ---
import uuid
from django.db import migrations, models
import django.db.models.deletion

# --- PASO 2: CREAR ESTA FUNCIÓN ---
# Esta función generará los códigos únicos para las reservas que ya existen
def gen_uuid(apps, schema_editor):
    Reserva = apps.get_model('booking', 'Reserva')
    for row in Reserva.objects.all():
        row.numero_reserva = uuid.uuid4().hex[:8].upper()
        row.save(update_fields=['numero_reserva'])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reserva_dias_reserva_espacio_techado'),
    ]

    operations = [
        # --- PASO 3: TUS OPERACIONES ORIGINALES (NO CAMBIAN) ---
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Porcentaje de descuento (e.g., 10 para 10%)')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.coupon'),
        ),
        
        # --- PASO 4: MODIFICACIÓN CLAVE (dividido en 3 partes) ---
        
        # 4.1. Crea el campo numero_reserva permitiendo que sea nulo TEMPORALMENTE
        migrations.AddField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        
        # 4.2. Ejecuta nuestra función para rellenar los valores de las filas existentes
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),

        # 4.3. Altera el campo para que ya NO permita nulos y sea como lo definiste en tu modelo
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]